title: Jon Duarte # your name (or website title) here
logo: "/images/Jon_Duarte.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "How's the water?"
  <br><br>
  "Don't be a d***"
  <br><br>
  "Everyone is going through their own mess. Be kind always"
  <a href="https://www.linkedin.com/in/jonjpbm/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-QEYVEQE701 # your Google Analytics tracking ID here
